/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.kereta.api.kai;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rangga darmajati 
 * @email rangga.darmajati@wgs.co.id
 * @gitlab @ranggadj
 * @whatsapp 085721731478
 *
 */
public final class FormTiket extends javax.swing.JFrame {
    
    // deklarasi
    Connection con;
    Statement stat;
    PreparedStatement pst = null;
    ResultSet rs;
    String sql;
    String url;
    int idKelas;
    int Selected;
    int totalharga;

    /**
     * Creates new form FormTiket
     */
    public FormTiket() {
        initComponents();
        ConnectionDB DB = new ConnectionDB();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        pst = DB.pst;
        tampil_combo_st_asal();
        tampil_combo_st_tujuan();
        getTotalHarga();
        idtkt.setVisible(false);
        id_order.setVisible(false);
        CreateUpdateDelete("get_all");
        BtnHapus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NamaPemesan = new javax.swing.JTextField();
        jComboBoxStasiunAsal = new javax.swing.JComboBox<>();
        jComboBoxStasiunTujuan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TGLBERANGKAT = new com.toedter.calendar.JCalendar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jml_dws = new javax.swing.JSpinner();
        jml_by = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        nama_penumpang = new javax.swing.JTextField();
        no_ktp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kls_ekonomi = new javax.swing.JRadioButton();
        kls_bisnis = new javax.swing.JRadioButton();
        kls_executive = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        kode_kereta = new javax.swing.JTextField();
        nama_kereta = new javax.swing.JTextField();
        total_harga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnSimpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTiket = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        idtkt = new javax.swing.JTextField();
        id_order = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PT. Kereta API Indonesai (KAI)");
        setLocationByPlatform(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("FORM PEMBELIAN TIKET KERETA API"));

        jLabel1.setText("TANGGAL KEBERANGKATAN");

        jLabel2.setText("NAMA PEMESAN");

        jLabel3.setText("STASIUN ASAL");

        jLabel4.setText("STASIUN TUJUAN");

        jLabel5.setText("JADWAL KEBERANGKATAN");

        jLabel6.setText("JUMLAH PENUMPANG");

        jLabel7.setText("DEWASA");

        jml_dws.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jml_dwsStateChanged(evt);
            }
        });
        jml_dws.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jml_dwsKeyTyped(evt);
            }
        });

        jLabel8.setText("BAYI");

        no_ktp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                no_ktpKeyTyped(evt);
            }
        });

        jLabel9.setText("NAMA PENUMPANG");

        jLabel10.setText("NO KTP");

        kls_ekonomi.setText("EKONOMI");
        kls_ekonomi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kls_ekonomiItemStateChanged(evt);
            }
        });

        kls_bisnis.setText("BISNIS");
        kls_bisnis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kls_bisnisItemStateChanged(evt);
            }
        });

        kls_executive.setText("EXECUTIVE");
        kls_executive.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kls_executiveItemStateChanged(evt);
            }
        });

        jLabel11.setText("KELAS");

        jLabel12.setText("KODE KERETA");

        jLabel13.setText("NAMA KERETA");

        jLabel14.setText("TOTAL HARGA RP.");

        kode_kereta.setEditable(false);
        kode_kereta.setBackground(java.awt.Color.lightGray);
        kode_kereta.setForeground(java.awt.Color.white);

        nama_kereta.setEditable(false);
        nama_kereta.setBackground(java.awt.Color.lightGray);
        nama_kereta.setForeground(java.awt.Color.white);

        total_harga.setEditable(false);
        total_harga.setBackground(java.awt.Color.lightGray);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "No KTP", "Nama Penumpang", "Jadwal Berangkat", "Stasiun Asal", "Stasiun Tujuan", "Kelas", "Kereta"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BtnSimpan.setText("SIMPAN");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        jButton2.setText("BATAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BtnHapus.setText("HAPUS");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        jButton4.setText("KELUAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTableTiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Stasiun Asal", "Stasiun Akhir", "Tanggal Berangkat", "Jam Berangkat", "Jam Tiba", "Kereta", "Tiket Tersedia"
            }
        ));
        jTableTiket.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTiketMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTiket);

        jButton5.setText("Cari Tiket");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        idtkt.setToolTipText("");
        idtkt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idtkt.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(idtkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NamaPemesan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxStasiunAsal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxStasiunTujuan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TGLBERANGKAT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BtnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kls_executive)
                                .addGap(42, 42, 42)
                                .addComponent(kls_bisnis)
                                .addGap(49, 49, 49)
                                .addComponent(kls_ekonomi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jml_dws, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(no_ktp, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jml_by, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nama_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nama_kereta, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kode_kereta, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NamaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxStasiunAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxStasiunTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TGLBERANGKAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(idtkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jml_dws, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jml_by, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nama_penumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(no_ktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kls_ekonomi)
                            .addComponent(kls_bisnis)
                            .addComponent(kls_executive)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(kode_kereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama_kereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(id_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(jButton2)
                    .addComponent(BtnHapus)
                    .addComponent(jButton4))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        // TODO add your handling code here:
        ValidasiForm();
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setNullValue();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void ValidasiAngka(KeyEvent b)
    {
        if(Character.isAlphabetic(b.getKeyChar())){
            b.consume();
            JOptionPane.showMessageDialog(null, "Inputan hanya boleh angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void ValidasiForm(){
        if(NamaPemesan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nama Pemesan tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
            NamaPemesan.requestFocus();
        }else if(jComboBoxStasiunAsal.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "Stasiun Asal harus dipilih", "Peringatan", JOptionPane.WARNING_MESSAGE);
            jComboBoxStasiunAsal.requestFocus();
        }else if(jComboBoxStasiunTujuan.getSelectedItem().equals("")){
            jComboBoxStasiunTujuan.requestFocus();
        }else if(kode_kereta.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tiket Kereta harus dipilih", "Peringatan", JOptionPane.WARNING_MESSAGE);
            jTableTiket.requestFocus();
        }else if((int) jml_dws.getValue() < 1){
            JOptionPane.showMessageDialog(null, "Jumlah Penumpang Dewasa harus diisi", "Peringatan", JOptionPane.WARNING_MESSAGE);
            jml_dws.requestFocus();
        }else if(nama_penumpang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nama Penumpang tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
            nama_penumpang.requestFocus();
        }else if(no_ktp.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No KTP tidak boleh kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
            no_ktp.requestFocus();
        }else if(kls_executive.isSelected() == false && kls_bisnis.isSelected() == false && kls_ekonomi.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Kelas harus dipilih", "Peringatan", JOptionPane.WARNING_MESSAGE);
            kls_executive.requestFocus();
        }else{
            if (JOptionPane.showConfirmDialog(null, "Apakah Data Yang Anda sudah benar ?", "Peringatan", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                CreateUpdateDelete("create");
                CreateUpdateDelete("get_all");
                setNullValue();
            }
        }
    }
    
    public void setNullValue()
    {
        NamaPemesan.setText(null);
        jComboBoxStasiunAsal.setSelectedItem("");
        jComboBoxStasiunTujuan.setSelectedItem("");
        jml_dws.setValue(0);
        nama_penumpang.setText(null);
        no_ktp.setText(null);
        kls_executive.setSelected(false);
        kls_bisnis.setSelected(false);
        kls_ekonomi.setSelected(false);
        kode_kereta.setText(null);
        nama_kereta.setText(null);
        total_harga.setText("0");
        DefaultTableModel tbl= new DefaultTableModel();
        tbl.addColumn("Id");
        tbl.addColumn("Stasiun Asal");
        tbl.addColumn("Stasiun Tujuan");
        tbl.addColumn("Tanggal Berangkat");
        tbl.addColumn("Jam Berangkat");
        tbl.addColumn("Jam Tiba");
        tbl.addColumn("Kereta");
        tbl.addColumn("Kursi Tersedia");
        jTableTiket.setModel(tbl);
        tbl.removeRow(2);
    }
    
    public void CreateUpdateDelete(String type)
    {
        switch (type) {
            case "create":
                try{
                    sql = "INSERT INTO `t_order` (`no_ktp`, `nama_pemesan`, `nama_penumpang`, `id_tiket`, `id_kelas`) VALUES (?,?,?,?,?)";
                    pst=con.prepareStatement(sql);
                    pst.setString(1, no_ktp.getText());
                    pst.setString(2, NamaPemesan.getText());
                    pst.setString(3, nama_penumpang.getText());
                    pst.setString(4, idtkt.getText());
                    pst.setInt(5, idKelas);
                    pst.execute();
                    
                    JOptionPane.showMessageDialog(this, "Data Berhasil disimpan.");
                } catch (SQLException err){
                    JOptionPane.showMessageDialog(this, err.getMessage());
                }
                break;
            case "hapus":
                try{
                    sql = "DELETE FROM `t_order` WHERE id=?";
                    pst=con.prepareStatement(sql);
                    pst.setString(1, id_order.getText());
                    pst.execute();
                    JOptionPane.showMessageDialog(this, "Data Berhasil dihapus.");
                } catch (SQLException err) {
                    JOptionPane.showMessageDialog(this, err.getMessage());
                }   break;
            case "get_all":
                DefaultTableModel tb= new DefaultTableModel();
                tb.addColumn("Id");
                tb.addColumn("No Ktp");
                tb.addColumn("Nama Penumpang");
                tb.addColumn("Jadwal Berangkat");
                tb.addColumn("Stasiun Asal");
                tb.addColumn("Stasiun Tujuan");
                tb.addColumn("Kelas");
                tb.addColumn("Kereta");
                jTable1.setModel(tb);
                try{
                    sql = "SELECT \n" +
                            "tor.id, tor.no_ktp, \n" +
                            "tor.nama_penumpang, \n" +
                            "concat(tt.tgl_brangkat,\" \", tt.jam_brangkat, \" - \", tt.jam_tiba) as jadwal_berangkat, \n" +
                            "ts.nama st_asal, \n" +
                            "tst.nama st_tujuan, \n" +
                            "tkls.nama kelas,\n" +
                            "tk.nama kereta\n" +
                            "FROM `t_order` tor\n" +
                            "JOIN t_tiket tt ON tt.id = tor.id_tiket\n" +
                            "JOIN t_kelas tkls ON tkls.id = tor.id_kelas\n" +
                            "JOIN t_stasiun ts ON ts.id = tt.id_st_asal\n" +
                            "JOIN t_stasiun tst ON tst.id = tt.id_st_tujuan\n" +
                            "JOIN t_kereta tk ON tt.id_kereta = tk.id";
                    pst =con.prepareStatement(sql);
                    rs = pst.executeQuery();
                    
                    while(rs.next()){
                        tb.addRow(new Object[]{
                            rs.getString("id"),
                            rs.getString("no_ktp"),
                            rs.getString("nama_penumpang"),
                            rs.getString("jadwal_berangkat"),
                            rs.getString("st_asal"),
                            rs.getString("st_tujuan"),
                            rs.getString("kelas"),
                            rs.getString("kereta")
                        });
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }   break;
            default:
                break;
        }
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String st_asal = (String) jComboBoxStasiunAsal.getSelectedItem();
        String st_tujuan = (String) jComboBoxStasiunTujuan.getSelectedItem();
        getTiketListCount(st_asal, st_tujuan);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTableTiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTiketMouseClicked
        // TODO add your handling code here:
        int SelRow =  jTableTiket.getSelectedRow();
        Object value = jTableTiket.getValueAt(SelRow, 0);
        getDetailTiket((String) value);
    }//GEN-LAST:event_jTableTiketMouseClicked

    public void getDetailTiket(String id)
    {
        System.out.println(id);
        try{
            sql = "SELECT \n" +
                  "tt.id, \n" +
                  "ts.nama stasiun_asal, \n" +
                  "tst.nama stasiun_akhir, \n" +
                  "tt.tgl_brangkat, \n" +
                  "tk.nama kereta, \n" +
                  "tk.kode kd_kereta, \n" +
                  "tt.jam_brangkat, \n" +
                  "tt.jam_tiba, \n" +
                  "tt.qty kursi_tersedia \n" +
                  "FROM `t_tiket` tt \n" +
                  "JOIN t_stasiun ts ON ts.id = tt.id_st_asal\n" +
                  "JOIN t_stasiun tst ON tst.id = tt.id_st_tujuan\n" +
                  "JOIN t_kereta tk ON tk.id = tt.id_kereta \n" +
                  "WHERE tt.id= ?";
            pst=con.prepareStatement(sql);
                pst.setString(1, id);
            rs =pst.executeQuery();
            rs.next();
            String kd_kereta = rs.getString("kd_kereta");
            String nm_kereta = rs.getString("kereta");
            idtkt.setText(rs.getString("id"));
            kode_kereta.setText(kd_kereta);
            nama_kereta.setText(nm_kereta);
            
            rs.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void kls_executiveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kls_executiveItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Your selected code here.
            System.out.println("kls_executive selected");
            Selected = 150000;
            idKelas = 1;
            getTotalHarga();
            kls_bisnis.setSelected(false);
            kls_ekonomi.setSelected(false);
        }
        else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            // Your deselected code here.
            System.out.println("kls_executive Deselected");
        }
    }//GEN-LAST:event_kls_executiveItemStateChanged

    private void kls_bisnisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kls_bisnisItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Your selected code here.
            System.out.println("kls_bisnis selected");
            Selected = 130000;
            idKelas = 2;
            getTotalHarga();
            kls_executive.setSelected(false);
            kls_ekonomi.setSelected(false);
        }
        else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            // Your deselected code here.
            System.out.println("kls_bisnis Deselected");
        }
    }//GEN-LAST:event_kls_bisnisItemStateChanged

    private void kls_ekonomiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kls_ekonomiItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Your selected code here.
            System.out.println("kls_ekonomi selected");
            Selected = 110000;
            idKelas = 3;
            getTotalHarga();
            kls_executive.setSelected(false);
            kls_bisnis.setSelected(false);
        }
        else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            // Your deselected code here.
            System.out.println("kls_ekonomi Deselected");
        }
    }//GEN-LAST:event_kls_ekonomiItemStateChanged

    private void jml_dwsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jml_dwsStateChanged
        // TODO add your handling code here:
        getTotalHarga();
    }//GEN-LAST:event_jml_dwsStateChanged

    private void no_ktpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_ktpKeyTyped
        // TODO add your handling code here:
        ValidasiAngka(evt);
        
    }//GEN-LAST:event_no_ktpKeyTyped

    private void jml_dwsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jml_dwsKeyTyped
        // TODO add your handling code here:
        ValidasiAngka(evt);
    }//GEN-LAST:event_jml_dwsKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Keluar?", "Peringatan", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        CreateUpdateDelete("hapus");
        CreateUpdateDelete("get_all");
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int SelRow =  jTable1.getSelectedRow();
        Object value = jTable1.getValueAt(SelRow, 0);
        id_order.setText((String) value);
        BtnHapus.setEnabled(true);
        
    }//GEN-LAST:event_jTable1MouseClicked

    public void getTotalHarga()
    {
        totalharga = (int) Selected * (int)jml_dws.getValue();
        total_harga.setText(Integer.toString(totalharga));
    }
    
    public void getTiketListCount(String sta, String stu)
    {
        java.util.Date Tglberangkat = TGLBERANGKAT.getDate();
        java.sql.Date tgl_berangkat = new java.sql.Date(Tglberangkat.getTime());
        try{
            sql = "SELECT \n" +
                  "count(tt.id) as rowcount \n" +
                  "FROM `t_tiket` tt \n" +
                  "JOIN t_stasiun ts ON ts.id = tt.id_st_asal\n" +
                  "JOIN t_stasiun tst ON tst.id = tt.id_st_tujuan\n" +
                  "JOIN t_kereta tk ON tk.id = tt.id_kereta\n" +
                  "WHERE ts.nama = ? AND tst.nama = ? and tt.tgl_brangkat= ?";
            pst=con.prepareStatement(sql);
                pst.setString(1, sta);
                pst.setString(2, stu);
                pst.setDate(3, tgl_berangkat);
            rs =pst.executeQuery();
            rs.next();
            int count = rs.getInt("rowcount");
            rs.close();
            if(count < 1){
                JOptionPane.showMessageDialog(this, "Tiket untuk tanggal tersebut tidak tersedia!");
                DefaultTableModel tbl= new DefaultTableModel();
                tbl.addColumn("Id");
                tbl.addColumn("Stasiun Asal");
                tbl.addColumn("Stasiun Tujuan");
                tbl.addColumn("Tanggal Berangkat");
                tbl.addColumn("Jam Berangkat");
                tbl.addColumn("Jam Tiba");
                tbl.addColumn("Kereta");
                tbl.addColumn("Kursi Tersedia");
                jTableTiket.setModel(tbl);
                tbl.removeRow(2);
                
            }else{
                getTiket(sta, stu);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void getTiket(String sta, String stu)
    {
        DefaultTableModel tbl= new DefaultTableModel();
        tbl.addColumn("Id");
        tbl.addColumn("Stasiun Asal");
        tbl.addColumn("Stasiun Tujuan");
        tbl.addColumn("Tanggal Berangkat");
        tbl.addColumn("Jam Berangkat");
        tbl.addColumn("Jam Tiba");
        tbl.addColumn("Kereta");
        tbl.addColumn("Kursi Tersedia");
        jTableTiket.setModel(tbl);
        try{
            java.util.Date Tglberangkat = TGLBERANGKAT.getDate();
            java.sql.Date tgl_berangkat = new java.sql.Date(Tglberangkat.getTime());
            sql = "SELECT \n" +
                  "tt.id, \n" +
                  "ts.nama stasiun_asal, \n" +
                  "tst.nama stasiun_akhir, \n" +
                  "tt.tgl_brangkat, \n" +
                  "tk.nama kereta, \n" +
                  "tt.jam_brangkat, \n" +
                  "tt.jam_tiba, \n" +
                  "tt.qty kursi_tersedia \n" +
                  "FROM `t_tiket` tt \n" +
                  "JOIN t_stasiun ts ON ts.id = tt.id_st_asal\n" +
                  "JOIN t_stasiun tst ON tst.id = tt.id_st_tujuan\n" +
                  "JOIN t_kereta tk ON tk.id = tt.id_kereta\n" +
                  "WHERE ts.nama = ? AND tst.nama = ? and tt.tgl_brangkat= ?";
            pst=con.prepareStatement(sql);
                pst.setString(1, sta);
                pst.setString(2, stu);
                pst.setDate(3, tgl_berangkat);
            rs =pst.executeQuery();
            while(rs.next()){
               
                tbl.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("stasiun_asal"),
                    rs.getString("stasiun_akhir"),
                    rs.getString("tgl_brangkat"),
                    rs.getString("jam_brangkat"),
                    rs.getString("jam_tiba"),
                    rs.getString("kereta"),
                    rs.getString("kursi_tersedia")
                });
               
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void tampil_combo_st_asal()
    {
        try {
            sql = "SELECT * FROM `t_stasiun`";
            pst=con.prepareStatement(sql);
            rs = pst.executeQuery();
            jComboBoxStasiunAsal.addItem("");
            while(rs.next()){
                jComboBoxStasiunAsal.addItem(rs.getString("nama"));
            }
            
        } catch  (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void tampil_combo_st_tujuan()
    {
        try {
            sql = "SELECT * FROM `t_stasiun`";
            pst=con.prepareStatement(sql);
            rs = pst.executeQuery();
            jComboBoxStasiunTujuan.addItem("");
            while(rs.next()){
                jComboBoxStasiunTujuan.addItem(rs.getString("nama"));
            }
            
        } catch  (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JTextField NamaPemesan;
    private com.toedter.calendar.JCalendar TGLBERANGKAT;
    private javax.swing.JTextField id_order;
    private javax.swing.JTextField idtkt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBoxStasiunAsal;
    private javax.swing.JComboBox<String> jComboBoxStasiunTujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableTiket;
    private javax.swing.JSpinner jml_by;
    private javax.swing.JSpinner jml_dws;
    private javax.swing.JRadioButton kls_bisnis;
    private javax.swing.JRadioButton kls_ekonomi;
    private javax.swing.JRadioButton kls_executive;
    private javax.swing.JTextField kode_kereta;
    private javax.swing.JTextField nama_kereta;
    private javax.swing.JTextField nama_penumpang;
    private javax.swing.JTextField no_ktp;
    private javax.swing.JTextField total_harga;
    // End of variables declaration//GEN-END:variables
}
